"""Embodiment interfaces for MHRN perception-action experiments."""

from .actuator import ActuatorAdapter
from .actuator_hub import ActionRouter, ActuatorHub
from .agent import EmbodimentAgent
from .audit import ActionAuditRecord, ActionAuditTrail
from .connections import (
    ConnectionDescriptor,
    ConnectionKind,
    ConnectionStatus,
    RelationshipClass,
)
from .controlled import ControlledEmbodimentAgent, ControlledSensorAdapter
from .deterministic import DeterministicTargetEnvironment
from .environment import EnvironmentAdapter
from .gateway_runtime import (
    GatewayCondition,
    GatewayEdge,
    GatewayGuardError,
    GatewayJournalEvent,
    GatewayLimits,
    GatewayResourceMode,
    GatewayRuntime,
    GatewayRuntimeError,
    GatewayState,
    GatewayTopology,
    PreregistrationGuard,
)
from .interoception import (
    DriveState,
    FunctionalState,
    InteroceptionFrame,
    RegulatoryState,
    VitalSignal,
    derive_drives,
    derive_functional_state,
    derive_regulatory_state,
    normalize_vital_signals,
)
from .models import (
    ActionCommand,
    ActionReceipt,
    ActuatorResult,
    EmbodimentMetrics,
    EnvironmentKind,
    EnvironmentObservation,
    SensorFrame,
)
from .msba import (
    EmbodimentTreatmentProvenance,
    EnergyCoefficients,
    EnergyEstimate,
    EnergyObservation,
    EnergyState,
    Modality,
    ModalityProfile,
    MSBAGatewayConfig,
    ResourcePressure,
    SymbolFrame,
    allocation_gate,
    default_modality_profiles,
    energy_price,
    energy_state,
    energy_units,
    msba_contract,
    phase_coherence,
    phase_weighted_stdp,
    recommended_protection_policy,
    resource_pressure,
    visual_growth_probability,
)
from .neural_symbiosis import (
    AreaDescriptor,
    AreaKind,
    NetworkAreaAdapter,
    NeuralSymbiosisCatalog,
    PipelineDirection,
    PipelineTemplate,
    PlasticGatewayConfig,
    formation_probability,
    gate_signal,
    homeostatic_scale,
    pair_stdp_delta,
    pruning_probability,
    reward_modulated_delta,
)
from .pipeline import EmbodimentPipeline
from .real_body import ConnectionManager
from .registry import EmbodimentRegistry
from .sensor import SensorAdapter
from .sensor_activation import SensorActivationAudit, SensorActivationService
from .specialized_areas import (
    LATEST_MSBA_DATA,
    STAGE4_MIN_NEURONS,
    STAGE4_MIN_SYNAPSES,
    SpecializedAreaNetwork,
    SpecializedAreaSpec,
    default_specialized_areas,
    reference_probe_suite,
    specialized_area_contract,
)
from .system_sensor import (
    SystemSensorAdapter,
    host_system_readings,
    wall_clock_readings,
)
from .task_outcome import TaskOutcome, TaskOutcomeVerifier

__all__ = [
    "ActionCommand",
    "ActionReceipt",
    "ActuatorAdapter",
    "ActuatorHub",
    "ActionRouter",
    "ActuatorResult",
    "ActionAuditRecord",
    "ActionAuditTrail",
    "AreaDescriptor",
    "AreaKind",
    "ConnectionDescriptor",
    "ConnectionKind",
    "ConnectionManager",
    "ConnectionStatus",
    "EmbodimentAgent",
    "ControlledEmbodimentAgent",
    "ControlledSensorAdapter",
    "DeterministicTargetEnvironment",
    "EmbodimentMetrics",
    "EmbodimentRegistry",
    "EnvironmentAdapter",
    "EnvironmentKind",
    "EnvironmentObservation",
    "GatewayCondition",
    "GatewayEdge",
    "GatewayGuardError",
    "GatewayJournalEvent",
    "GatewayLimits",
    "GatewayResourceMode",
    "GatewayRuntime",
    "GatewayRuntimeError",
    "GatewayState",
    "GatewayTopology",
    "DriveState",
    "EnergyCoefficients",
    "EnergyEstimate",
    "EnergyObservation",
    "EnergyState",
    "EmbodimentTreatmentProvenance",
    "FunctionalState",
    "InteroceptionFrame",
    "MSBAGatewayConfig",
    "Modality",
    "ModalityProfile",
    "NetworkAreaAdapter",
    "NeuralSymbiosisCatalog",
    "PipelineDirection",
    "PipelineTemplate",
    "PlasticGatewayConfig",
    "PreregistrationGuard",
    "RegulatoryState",
    "ResourcePressure",
    "EmbodimentPipeline",
    "RelationshipClass",
    "SensorAdapter",
    "SensorActivationAudit",
    "SensorActivationService",
    "SensorFrame",
    "LATEST_MSBA_DATA",
    "STAGE4_MIN_NEURONS",
    "STAGE4_MIN_SYNAPSES",
    "SpecializedAreaNetwork",
    "SpecializedAreaSpec",
    "SymbolFrame",
    "TaskOutcome",
    "TaskOutcomeVerifier",
    "SystemSensorAdapter",
    "VitalSignal",
    "allocation_gate",
    "default_modality_profiles",
    "default_specialized_areas",
    "reference_probe_suite",
    "specialized_area_contract",
    "derive_drives",
    "derive_functional_state",
    "derive_regulatory_state",
    "energy_price",
    "energy_state",
    "energy_units",
    "formation_probability",
    "gate_signal",
    "homeostatic_scale",
    "host_system_readings",
    "msba_contract",
    "normalize_vital_signals",
    "pair_stdp_delta",
    "phase_coherence",
    "phase_weighted_stdp",
    "pruning_probability",
    "recommended_protection_policy",
    "resource_pressure",
    "reward_modulated_delta",
    "visual_growth_probability",
    "wall_clock_readings",
]
