"""Read-only AI assistance for scientific research artifacts."""

from .advisor import ActionProposal, CognitiveAdvisor
from .ai_research_object import (
    AIR_RESEARCH_QUESTIONS,
    AIResearchComparison,
    BlindAnalysis,
    BorrowedIntelligenceMetric,
    ModelInterpretation,
    ReviewerMetrics,
    borrowed_intelligence_ratio,
    interpretation_distance,
)
from .airr import (
    AIResearchReport,
    AIRRPipeline,
    render_markdown,
    write_artifact_review,
    write_human_review,
)
from .assistant import AnalysisBackend, ResearchAssistant
from .authority import (
    AIRole,
    AuthorityRule,
    authority_for,
    authority_matrix,
    validate_authority_matrix,
)
from .causal import CausalAttributionReport, generate_causal_attribution_report
from .chat import ChatBackend, ResearchChat, chat_backend_from_text_backend
from .contracts import (
    AIClockMode,
    AIExposure,
    AIInferenceFailureEvent,
    AIInteractionRecord,
    AIReproducibility,
    CausalTaint,
    EpistemicProvenanceGraph,
    Evidence,
    Interpretation,
    Intervention,
    Observation,
    Proposal,
    ProvenanceEdge,
    ProvenanceNode,
)
from .firewall import AIAuthority, AIFirewallViolation, AIResource, ScientificAIFirewall
from .gateways import (
    ApprovedIntervention,
    InterventionGateway,
    MemoryWriteGateway,
    MemoryWriteProposal,
)
from .governance import (
    ConfirmatoryRunLock,
    DataPartition,
    KnowledgeOrigin,
    NetworkMode,
    PreregistrationLock,
    PromptRegistry,
    ResearchRunMode,
    RetrievalRecord,
    VersionedPrompt,
    validate_data_leakage,
    validate_data_partition,
    validate_network_mode,
)
from .local_fallback_backend import (
    LocalFallbackBackend,
    create_local_fallback_backend,
)
from .models import AIAnalysisRecord, ResearchPacket
from .observation_stream import (
    ObservationStream,
    ObservationStreamError,
    ObservationStreamRecord,
)
from .replay_backend import FrozenAIReplayBackend, FrozenAIReplayError
from .shadow import (
    ShadowMode,
    ShadowProposalMetrics,
    ShadowResult,
    evaluate_shadow_proposals,
)
from .statistics import summarize, write_statistics

__all__ = [
    "AIAnalysisRecord",
    "AIR_RESEARCH_QUESTIONS",
    "AIResearchComparison",
    "BorrowedIntelligenceMetric",
    "BlindAnalysis",
    "ModelInterpretation",
    "ReviewerMetrics",
    "borrowed_intelligence_ratio",
    "interpretation_distance",
    "ActionProposal",
    "ApprovedIntervention",
    "AIAuthority",
    "AIFirewallViolation",
    "AIResource",
    "KnowledgeOrigin",
    "ConfirmatoryRunLock",
    "DataPartition",
    "InterventionGateway",
    "MemoryWriteGateway",
    "MemoryWriteProposal",
    "NetworkMode",
    "PreregistrationLock",
    "PromptRegistry",
    "RetrievalRecord",
    "VersionedPrompt",
    "ResearchRunMode",
    "validate_data_partition",
    "validate_data_leakage",
    "validate_network_mode",
    "AIExposure",
    "AIClockMode",
    "AIInferenceFailureEvent",
    "AIInteractionRecord",
    "AIReproducibility",
    "AnalysisBackend",
    "AIRRPipeline",
    "AIResearchReport",
    "AuthorityRule",
    "AIRole",
    "ResearchAssistant",
    "ResearchPacket",
    "CognitiveAdvisor",
    "FrozenAIReplayBackend",
    "FrozenAIReplayError",
    "LocalFallbackBackend",
    "create_local_fallback_backend",
    "ShadowMode",
    "ShadowProposalMetrics",
    "ShadowResult",
    "evaluate_shadow_proposals",
    "ObservationStream",
    "ObservationStreamError",
    "ObservationStreamRecord",
    "render_markdown",
    "write_human_review",
    "write_artifact_review",
    "summarize",
    "write_statistics",
    "ChatBackend",
    "CausalAttributionReport",
    "generate_causal_attribution_report",
    "ResearchChat",
    "chat_backend_from_text_backend",
    "CausalTaint",
    "Evidence",
    "EpistemicProvenanceGraph",
    "Intervention",
    "Interpretation",
    "Observation",
    "Proposal",
    "ProvenanceEdge",
    "ProvenanceNode",
    "ScientificAIFirewall",
    "authority_for",
    "authority_matrix",
    "validate_authority_matrix",
]
