#!/usr/bin/env python3
from pathlib import Path

path = Path("src/research_assistant/airr.py")
text = path.read_text(encoding="utf-8")
old = '''def _packet_protocol(packet: ResearchPacket) -> str:\n    """Resolve the protocol identifier from canonical packet/manifest fields."""\n    protocol_payload = packet.protocol if isinstance(packet.protocol, dict) else {}\n    simulation = (\n        packet.manifest.get("simulation", {})\n        if isinstance(packet.manifest.get("simulation"), dict)\n        else {}\n    )\n    return str(\n        protocol_payload.get("protocol")\n        or simulation.get("protocol")\n        or packet.manifest.get("protocol_id")\n        or "NOT_AVAILABLE"\n    )\n\n\ndef _packet_semantic_status(packet: ResearchPacket) -> tuple[str, str]:\n    """Resolve deterministic RQ/protocol/condition alignment from packet data."""\n    question_id = str(packet.research_question.get("id", "NOT_AVAILABLE"))\n    protocol = _packet_protocol(packet)\n\n    conditions: set[str] = set()\n    data = packet.data if isinstance(packet.data, dict) else {}\n    statistics = data.get("statistics")\n    if isinstance(statistics, dict):\n        statistics_conditions = statistics.get("conditions")\n        if isinstance(statistics_conditions, dict):\n            conditions.update(str(name) for name in statistics_conditions)\n\n    for key in ("run_preview", "runs"):\n        values = data.get(key)\n        if not isinstance(values, list):\n            continue\n        for value in values:\n            if isinstance(value, dict) and value.get("condition") is not None:\n                conditions.add(str(value["condition"]))\n\n    return classify_semantic_status(question_id, protocol, conditions)\n'''
new = '''def _packet_protocol(packet: ResearchPacket) -> str:\n    """Resolve the protocol identifier from canonical packet/manifest fields."""\n    protocol_payload: dict[str, Any] = (\n        packet.protocol if isinstance(packet.protocol, dict) else {}\n    )\n    simulation_raw: object = packet.manifest.get("simulation")\n    simulation: dict[str, Any] = (\n        cast(dict[str, Any], simulation_raw)\n        if isinstance(simulation_raw, dict)\n        else {}\n    )\n    return str(\n        protocol_payload.get("protocol")\n        or simulation.get("protocol")\n        or packet.manifest.get("protocol_id")\n        or "NOT_AVAILABLE"\n    )\n\n\ndef _packet_semantic_status(packet: ResearchPacket) -> tuple[str, str]:\n    """Resolve deterministic RQ/protocol/condition alignment from packet data."""\n    question_id = str(packet.research_question.get("id", "NOT_AVAILABLE"))\n    protocol = _packet_protocol(packet)\n\n    conditions: set[str] = set()\n    data: dict[str, Any] = packet.data if isinstance(packet.data, dict) else {}\n    statistics_raw: object = data.get("statistics")\n    if isinstance(statistics_raw, dict):\n        statistics = cast(dict[str, Any], statistics_raw)\n        statistics_conditions_raw: object = statistics.get("conditions")\n        if isinstance(statistics_conditions_raw, dict):\n            statistics_conditions = cast(\n                dict[str, Any], statistics_conditions_raw\n            )\n            conditions.update(str(name) for name in statistics_conditions)\n\n    for key in ("run_preview", "runs"):\n        values_raw: object = data.get(key)\n        if not isinstance(values_raw, list):\n            continue\n        values = cast(list[object], values_raw)\n        for value_raw in values:\n            if not isinstance(value_raw, dict):\n                continue\n            value = cast(dict[str, Any], value_raw)\n            condition = value.get("condition")\n            if condition is not None:\n                conditions.add(str(condition))\n\n    return classify_semantic_status(question_id, protocol, conditions)\n'''
if new not in text:
    if old not in text:
        raise SystemExit("AIRR semantic helper anchor not found")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("patched AIRR typing")
